global:
  scrape_interval:     10s
  evaluation_interval: 30s
rule_files:
scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'quarkus'
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'quarkus2'
  static_configs:
    - targets: ['localhost:8180']

